---
title: "Práctica 11: Anotación Estructural"
author: "María Ruiz Ventura"
lang: es
date: today
execute: 
  output: true
  error: true
  warning: false
engine: knitr
format:
  html:
    embed-resources: true
    theme: cosmo
    toc: true
---

## Introducción

En esta práctica vamos a trabajar con los resultados de la anotación estructural realizada sobre el ensamblaje del cromosoma 4 de *Arabidopsis thaliana*. 

Dado que los procesos completos de anotación (con programas como RepeatModeler, RepeatMasker y GALBA) son computacionalmente muy costosos para los ordenadores virtuales de clase, trabajaremos directamente procesando los archivos de entrada y explorando los resultados pre-calculados que nos proporciona el profesor.

---
:::{.callout-note icon=false}
# Ejercicio 1: Limpieza de cabeceras de proteínas

```{bash}
if [ ! -f proteinas.fasta ]; then
awk '(/^>/){split($1, A, /\|/); print ">" A[2]}(/^[^>]/){print $0}' ../../data/proteinas.fasta > proteinas.fasta
fi
```

:::

## Análisis de los resultados de RepeatModeler

RepeatModeler fue ejecutado de la manera siguiente:

# Paso previo para convertir el ensamblaje en una base de datos de BLAST:

BuildDatabase -name At4 ../2026-04-16/asm1/At4.fa

RepeatModeler -database At4 -threads 6 >& run.log

Puedes descargar y descomprimir los resultados de RepeatModeler desde el aula virtual a la carpeta de trabajo actual (como si fueran resultados tuyos). Encontrarás la estructura de archivos siguiente:

.
├── At4-families.fa               
├── At4-families.stk   
├── At4.nhr                     
├── At4.nin                           
├── At4.njs                           
├── At4.nnd                              
├── At4.nni               
├── At4.nog              
├── At4.nsq              
├── At4-rmod.log
├── At4.translation 
├── RM_358880.MonApr202033152026
│   ├── consensi.fa
│   ├── families.stk
│   ├── genome.2bit
│   ├── rmod.log
│   ├── round-1
│   ├── round-2
│   └── round-3
└── run.log

:::{.callout-note icon=false}
# Ejercicio 2

Explora los resultados de RepeatModeler y trata de contestar las preguntas siguientes.

1. ¿Cuántas familias de elementos transponibles se han encontrado?

```{bash}
grep -c "^>" RepeatModelerResults/At4-families.fa
```

2. ¿Cuánto duró la ejecución del programa?

```{bash}
grep "Program Time" RepeatModelerResults/At4-rmod.log
```

3. ¿Cuál dirías que es el archivo de salida más importante?

El archivo más importante es consensi.fa (o At4-families.fa), ya que contiene las secuencias consenso de las familias de elementos transponibles identificadas. Este archivo es el que se utiliza posteriormente como librería para que RepeatMasker pueda localizar y enmascarar esas repeticiones en el genoma
    
:::

## Suavizar la máscara

RepeatMasker fue ejecutado así:

RepeatMasker -lib At4-families.fa -dir RM01 -gtf ../../data/At4.fa

Encontrarás la carpeta (comprimida) de resultados de RepeatMasker en el aula virtual. Descárgala y descomprimela en la carpeta de trabajo actual. La versión enmascarada tiene una máscara dura (RepeatMasker ha sustituído todos los elementos trasponibles y repeticiones por Ns), con lo que se ha perdido la información de la secuencia original en esas regiones. El programa GALBA recomienda partir de un ensamblaje con máscara suave, donde las regiones repetitivas están marcadas con letra minúscula. Para convertir la máscara dura en una máscara suave, utilizaremos bedtools.

:::{.callout-note icon=false}
# Ejercicio 3

Instala el programa bedtools siguiendo las instrucciones oportunas para tu sistema en la página oficial

Utiliza el ensamblaje original como archivo FASTA de entrada y el archivo GFF que ha producido RepetaMasker como coordenadas de las regiones a enmascarar. Lee el manual de bedtools maskfasta en este enlace y genera el ensamblaje con máscara suave llamado At4.soft.fa.

```{bash}
if [ ! -e At4.soft.fa ]; then
  ./bedtools maskfasta \
    -soft \
    -fi ../2026-04-15/asm1/At4.fa \
    -fo At4.soft.fa \
    -bed RepeatMaskerResults/RM01/At4.fa.out.gff
fi
```

:::

## GALBA

Para ejecutar GALBA ha sido necesario crear algunas variables de entorno que indican donde puede GALBA encontrar un par de ejecutables más. Para facilitar la reproducibilidad, este tipo de definiciones deben aparecer al principio del bloque, donde son más visibles, para que sean fácilmente modificadas cuando las órdenes vayan a ejecutarse en otro ordenador.

export TSEBRA_PATH=/home/joiglu/bin/TSEBRA/bin/
export MINIPROTHINT_PATH=/home/joiglu/bin/miniprothint/

galba.pl --species="Arabidopsis thaliana" \
         --genome=At4.soft.fa \
         --prot_seq=proteinas.fasta

:::{.callout-note icon=false}
# Ejercicio 4

Incluye en tu documento de Quarto un bloque de código (pero no ejecutable, con la opción eval: false) como el anterior, donde los caminos TSERBA y a MINIPROTHINT se correspondan con tu propia carpeta bin, aunque no los tengas instalados.

Encontrarás los resultados de GALBA en la carpeta comprimida galba.zip, en el aula virtual.

```{bash}
#| label: ejercicio-4
#| eval: false

# Rutas a las herramientas (aunque no las tengamos instaladas)
export TSEBRA_PATH=$HOME/bin/TSEBRA/bin/
export MINIPROTHINT_PATH=$HOME/bin/miniprothint/

# Comando principal de GALBA
galba.pl --species="Arabidopsis thaliana" \
  --genome At4.soft.fa \
  --prot_seq proteinas.fasta
```
:::

:::{.callout-note icon=false}
# Ejercicio 5

Échales un vistazo a los archivos de salida de GALBA y trata de sacar algo en claro.

Al revisar los resultados pre-calculados de GALBA (específicamente el archivo de anotación augustus.hints.gff3 que se encuentra en galba.zip), podemos observar cómo el programa ha logrado predecir la estructura de los genes a lo largo del cromosoma.

En este archivo GFF3 se detallan claramente las coordenadas exactas de:

    Los genes predichos, indicando en qué cadena (positiva o negativa) se encuentran.

    Los exones (diferenciando entre initial, internal y terminal).

    Las regiones CDS (las secuencias codificantes que finalmente se traducen a proteína).

    Los intrones (las regiones que se eliminan mediante splicing).

El hecho de haber utilizado proteínas conocidas de la misma especie como "pistas" (hints) mejora drásticamente la precisión de estas predicciones estructurales en comparación con métodos puramente ab initio (predicción a ciegas solo con la secuencia de ADN).

:::

:::{.callout-note icon=false}
# Ejercicio 6

Si quieres, puedes intentar instalar GALBA en tu ordenador, tomando nota de las dificultades con las que te encuentras.

Instalar herramientas bioinformáticas complejas como GALBA desde cero suele ser un proceso muy tedioso. Las principales dificultades incluyen:

    Múltiples dependencias: GALBA no es un programa independiente, sino un "pipeline" que necesita coordinar otros programas como Augustus, miniprothint, TSEBRA, Samtools y Bamtools. Si uno falla, GALBA falla.

    Problemas de compilación: Programas como Augustus están escritos en C++ y requieren ser compilados (make) en el ordenador destino, lo que muchas veces lanza errores si faltan librerías específicas del sistema (como Boost o Zlib).

    Gestión de variables de entorno: Es fundamental configurar correctamente los PATH para que los distintos scripts escritos en Perl y Python sepan dónde encontrar los binarios de los otros programas (como se ha visto en el código del Ejercicio 4).

Falta de permisos: En ordenadores compartidos (como el entorno virtual de la universidad), la imposibilidad de usar el comando sudo impide instalar dependencias globales, obligando a compilar todo localmente en la carpeta del usuario, lo que complica aún más el proceso.
:::

## Referencias
Bruna, T., H. Li, J. Guhlin, D. Honsel, S. Herbold, M. Stanke, N. Nenasheva, M. Ebel, L. Gabriel, and K. J. Hoff. 2023. “Galba: Genome Annotation with Miniprot and AUGUSTUS.” BMC Bioinformatics 24: 327. https://doi.org/10.1186/s12859-023-05449-z.
Flynn, Jullien M., Robert Hubley, Clément Goubert, Jeb Rosen, Andrew G. Clark, Cédric Feschotte, and Arian F. Smit. 2020. “RepeatModeler2 for Automated Genomic Discovery of Transposable Element Families.” Proceedings of the National Academy of Sciences 117 (17): 9451–57. https://doi.org/10.1073/pnas.1921046117.
Li, Heng. 2023. “Protein-to-Genome Alignment with Miniprot.” Bioinformatics 39 (1): btad014. https://doi.org/10.1093/bioinformatics/btad014.




